vanda/vam-fractal

src/assets/svg/tick-mark.svg
src/components/base/icons/icons.config.js
src/components/base/typography/_typography.scss

Please read the following about fonts: https://web.dev/font-display/?utm_source=lighthouse&utm_medium=node

Add icons and extend fonts

---

src/assets/scripts/vam-scripts.js
src/assets/styles/vam-style.scss
src/components/blocks/search-pagination/_search-pagination.js
src/components/blocks/search-pagination/search-pagination.html
src/components/blocks/search-pagination/search-pagination.scss
src/components/blocks/search-results/_search-results.scss
src/components/blocks/search-results/search-results.config.js
src/components/blocks/search-results/search-results.html
src/components/groups/search-box-container/search-box-container.html
src/components/groups/search-results-page/_search-results-page.scss
src/components/groups/search-results-page/search-results-page.config.js

many small fixes and also making sure the page actually works

Stc2 247 fixing and rewriting listing page

---

src/assets/scripts/vam-scripts.js
src/components/blocks/search-results/_search-results.js
src/components/blocks/search-results/_search-results.scss
src/components/blocks/search-results/search-results.config.js
src/components/blocks/search-results/search-results.html
src/components/groups/search-results-page/search-results-page.config.js

Stc2 221 offensive search listings

---

.circleci/config.yml
.gitignore
package-lock.json
package.json

Adding CircleCI for testing and branch deploys.

Circleci setup

---

src/assets/scripts/vam-scripts.js
src/assets/styles/vam-style.scss
src/components/blocks/object-card/_object-card.scss
src/components/blocks/object-card/object-card.config.js
src/components/blocks/object-card/object-card.html
src/components/groups/object-grid/_object-grid.scss
src/components/groups/object-grid/object-grid.config.js
src/components/groups/object-grid/object-grid.html
src/components/services/lazyload-blur/_lazyload-blur.scss
src/components/services/lazyload-blur/lazyload-blur.config.js
src/components/services/lazyload-blur/lazyload-blur.html

Modify object-card & object-grid for EtC;
add lazyload blur mechanism

EtC object-grid

---

src/components/blocks/facet-box/_facet-box.js
src/components/blocks/search-form/_search-form.scss
src/components/blocks/search-results/_search-results.scss
src/components/blocks/search-results/search-results.html

lots of various changes to search components for accessibility

Accessibility changes

---

src/components/blocks/facet-box/_facet-box.scss
src/components/blocks/facet-box/facet-box.html
src/components/blocks/search-results/_search-results.scss

- font weight adjustment to see more
- new responsive behaviour for search results
- new way of handling facet styling
- removing max width of term text in facet box mobile

facet box style adjustments

---

src/components/blocks/modal/_modal.js
src/components/blocks/modal/_modal.scss
src/components/blocks/modal/modal.html

- cannot tab outside of modal, close is now a link rather than pseudoelement
- add back in button for closing modal
- linting js

WEB 1602 fractal modal accessibility fix

---

src/components/blocks/newsletter-signup/_newsletter-signup.js
src/components/blocks/newsletter-signup/_newsletter-signup.scss
src/components/blocks/newsletter-signup/newsletter-signup.html

add aria-live to error message container, aria-invalid to input and border when input is wrong to make it extra clear

---

src/components/blocks/newsletter-signup/_newsletter-signup.scss

place holder color change to make contrast of text readable﻿

change contrast of placeholder in newsletter sign up for WEB-1778

---

src/components/blocks/icon-badge/_icon-badge.scss
src/components/blocks/image-credit/_image-credit.scss
src/components/blocks/promo/_promo.scss
src/components/blocks/section-header/_section-header.scss
src/components/blocks/site-nav/_site-nav.scss
src/components/blocks/site-nav/site-nav.html
src/components/groups/block-grid/_block-grid.scss

- add new skip to content button to nav
- add change block grid title text shadow, promo background color, text shadow to image credit, promo box and section header

WEB 1900 text contrast background imagery

---

src/components/blocks/site-nav/_site-nav.scss
src/components/blocks/site-nav/site-nav.html

newly designed skip content button added to nav in fractal

add new skip to content button to nav

---

src/components/blocks/newsletter-signup/_newsletter-signup.scss
src/components/blocks/newsletter-signup/newsletter-signup.config.js
src/components/blocks/newsletter-signup/newsletter-signup.html
src/components/blocks/site-footer/_site-footer.scss

new newsletter form for footer

---

src/components/blocks/event-teaser/_event-teaser.scss

update text contrast on even teaser﻿

update contrast on event teaser

---

src/assets/styles/vam-style.scss
src/components/blocks/beta-tag/_beta-tag.scss
src/components/blocks/collection-card/_collection-card.scss
src/components/blocks/image-overlay-license-modal/_image-overlay-license-modal.js
src/components/blocks/image-overlay-license-modal/_image-overlay-license-modal.scss
src/components/blocks/image-overlay-license-modal/image-overlay-license-modal.html
src/components/blocks/newsletter-signup/_newsletter-signup.scss
src/components/blocks/object-card/_object-card.scss
src/components/blocks/object-shuffler/_object-shuffler.js
src/components/blocks/object-shuffler/_object-shuffler.scss
src/components/blocks/programme-page-tout/_programme-page-tout.scss
src/components/blocks/promo/_promo.scss
src/components/blocks/search-form/_search-form.js
src/components/blocks/search-form/_search-form.scss
src/components/blocks/search-form/search-form.html
src/components/blocks/search-results/_search-results.scss
src/components/blocks/search-results/search-results.html
src/components/blocks/site-nav/_site-nav.scss
src/components/blocks/toggle-nav/_toggle-nav.scss
src/components/groups/block-grid/_block-grid.scss
src/components/mixins/focus/_focus.scss
src/components/mixins/focus/focus.html
src/components/services/themed/_themed.scss

- added focus style as a mixin
- overriding focus states
- fix add dates on collections landing accessibility
- fix focus on object shuffler when only one tab
- added inset focus for special cases
- focus override for exceptional elements

WEB 1888 double focus

---

src/components/blocks/newsletter-signup/_newsletter-signup.scss
src/components/blocks/newsletter-signup/newsletter-signup.html
src/components/blocks/site-footer/_site-footer.scss

Revert "WEB 1903 newsletter footer changes"

---

src/components/blocks/newsletter-signup/_newsletter-signup.scss
src/components/blocks/newsletter-signup/newsletter-signup.html
src/components/blocks/site-footer/_site-footer.scss

- newsletter footer flex adjustment
- newsletter footer mobile changes
- further flex adjustment to newsletter
- consolidiate changes made in etc-frontend into fractal
- correct template of newsletter based on feedback
- fix for footer newsletter field orientation on vam-web

WEB 1903 newsletter rebase dev final

---

src/components/blocks/image-carousel/image-carousel.scss

modify the hover/focus states for the image overlay﻿

update the focus states for image overlay

---

src/components/blocks/site-nav/_site-nav.js
src/components/blocks/site-nav/site-nav.html

added some aria attributes to improve accessibility in line with WEB-2121﻿

add aria expanded and aria labelledby to hamburger menu

---

src/components/blocks/image-carousel/image-carousel.scss
src/components/blocks/image-overlay-license-modal/_image-overlay-license-modal.js
src/components/blocks/image-overlay-license-modal/_image-overlay-license-modal.scss
src/components/blocks/image-overlay-license-modal/image-overlay-license-modal.html
src/components/blocks/site-nav/_site-nav.js

setting this up ahead of next deploy (whenever we also want to deploy this stuff)...

deploy to production

---

src/components/blocks/event-teaser/_event-teaser.scss

Update to vanda/vam-web#2146 to incorporate amends.

Update venue listing CSS

---

src/components/blocks/event-teaser/_event-teaser.scss
src/components/units/label-tag/_label-tag.scss
src/components/units/label-tag/label-tag.config.js

Update venue event-teaser panel styling

---

src/components/blocks/icon-badge/_icon-badge.scss
src/components/blocks/newsletter-signup/_newsletter-signup.scss
src/components/blocks/newsletter-signup/newsletter-signup.html
src/components/blocks/site-footer/_site-footer.scss

Issues: vanda/vam-web#1970 and vanda/vam-web#2224
These issues have been closed after Design QA.

Newsletter UI updates

---

src/components/blocks/icon-badge/_icon-badge.scss
src/components/blocks/site-footer/_site-footer.scss

Includes fixes for vanda/vam-web#2222 and vanda/vam-web#2223

Update typography settings

---

src/components/blocks/venue-card/_venue-card.scss
src/components/blocks/venue-card/venue-card.html

Update homepage venue card styling

---

src/components/blocks/newsletter-signup/newsletter-signup.html

Update venue landing page newsletter component copy

---

src/components/blocks/newsletter-signup/newsletter-signup.html

Venue landing page newsletter component privacy policy

---

src/components/blocks/event-teaser/_event-teaser.scss
src/components/blocks/venue-core-info/_venue-core-info.scss

Issues: vanda/vam-web#2439 and vanda/vam-web#2421

Update venue landing page styling

---

src/components/blocks/event-teaser/_event-teaser.scss

Update whats on event card styling

---

src/components/blocks/site-footer/_site-footer.scss

Update footer typography

---

src/components/blocks/site-nav/_site-nav.scss

Update primary site nav typography

---

src/components/blocks/site-nav/_site-nav.scss

Remove mobile nav from normal doc flow to allow content up

---

src/components/blocks/venue-visit-info/_venue-visit-info.scss

Remove css display property from media query to parent selector

---

src/components/blocks/newsletter-signup/_newsletter-signup.scss
src/components/groups/venue-card-grid/_venue-card-grid.scss

Issues: vanda/vam-web#2675 and vanda/vam-web#2676

Update heading typography

---

src/components/base/reset/_reset.scss

Add fall through content property for quote pseudo element

---

src/components/blocks/site-footer/_site-footer.scss

Update footer list styling

---

src/components/blocks/annotated-tour-preview/_annotated-tour-preview.scss

Issues: vanda/vam-web#2377 and vanda/vam-web#2378

Update annotated tour preview layout

---

src/components/blocks/newsletter-signup/newsletter-signup.html

Alter html class on global footer submit input

---

src/assets/styles/vam-style.scss
src/components/blocks/event-teaser/_event-teaser.scss
src/components/blocks/event-teaser/event-teaser.config.js
src/components/blocks/event-teaser/event-teaser.html
src/components/blocks/site-nav/site-nav.html
src/components/blocks/venue-teaser/_venue-teaser.scss
src/components/blocks/venue-teaser/venue-teaser.config.js
src/components/blocks/venue-teaser/venue-teaser.html
src/components/groups/block-grid/_block-grid.scss
src/components/groups/block-grid/block-grid.config.js
src/components/groups/block-grid/block-grid.html

depends on https://github.com/vanda/vam-web/pull/3015

MAS-256 MS Event teasers; WEB-2425 Venue teaser refactor

---

src/components/groups/object-grid/_object-grid.scss

Jira:
[https://vandam.atlassian.net/browse/MAS-307](https://vandam.atlassian.net/browse/MAS-307)

Update mobile object-grid columns

---

src/components/blocks/promo/_promo.scss

[https://vandam.atlassian.net/browse/MAS-304](https://vandam.atlassian.net/browse/MAS-304)

Alter promo banner font size

---

src/assets/scripts/vam-scripts.js
src/assets/styles/vam-style.scss
src/components/blocks/events-featured/_events-featured.js
src/components/blocks/events-featured/_events-featured.scss
src/components/blocks/events-featured/events-featured.config.js
src/components/blocks/events-featured/events-featured.html
src/components/mixins/breakpoints/_breakpoints.scss
src/components/units/label-tag/_label-tag.scss
src/components/units/label-tag/label-tag.config.js

[https://vandam.atlassian.net/browse/MAS-357](https://vandam.atlassian.net/browse/MAS-357)

Initial commit of featured events component

---

src/components/blocks/facet-box/_facet-box.js
src/components/blocks/image-row/_image-row.js

These are a couple of linting issues that were being picked up by jslint in Fractal v.1 and were causing errors in circle-CI when deploying to web-ms

Address linting errors

---

src/components/blocks/events-featured/_events-featured.js
src/components/blocks/events-featured/_events-featured.scss
src/components/blocks/facet-box/_facet-box.js

[https://vandam.atlassian.net/browse/WEB-2511](https://vandam.atlassian.net/browse/WEB-2511)

Modify narrow viewport scrolling details

---

src/components/blocks/event-teaser/_event-teaser.scss

https://vanda.slack.com/archives/C03RA0YKXS8/p1685635303035029 - checked off by Fiona

event-teser: tweak dark brder colors [MAS-381]

---

src/components/blocks/icon-list/_icon-list.scss

[https://vandam.atlassian.net/browse/MAS-341](https://vandam.atlassian.net/browse/MAS-341)

Update icon-list component styling

---

src/components/blocks/icon-list/_icon-list.scss
src/components/blocks/venue-card/_venue-card.scss
src/components/blocks/venue-card/venue-card.config.js
src/components/blocks/venue-card/venue-card.html
src/components/groups/venue-card-grid/_venue-card-grid.scss
src/components/units/link/_link.scss

Tycho-tied!
Only to be merged along with https://github.com/vanda/vam-web/pull/3196

MAS-372-379 venue card FOS Homepage changes + related tweaks

---

src/components/blocks/search-result-auto-suggest/_search-result-auto-suggest.scss
src/components/blocks/site-nav/_site-nav.js

to be merged with https://github.com/vanda/vam-web/pull/3210

site search auto suggest: add venue to events + exhibs

---

src/assets/styles/vam-style.scss
src/components/blocks/exhibition-promo/_exhibition-promo.scss
src/components/blocks/exhibition-promo/exhibition-promo.config.js
src/components/blocks/exhibition-promo/exhibition-promo.html
src/components/groups/exhibition-promo-grid/_exhibition-promo-grid.scss
src/components/groups/exhibition-promo-grid/exhibition-promo-grid.config.js
src/components/groups/exhibition-promo-grid/exhibition-promo-grid.html

[https://vandam.atlassian.net/browse/MAS-369](https://vandam.atlassian.net/browse/MAS-369)

Add featured exhibitions component

---

src/components/blocks/promo/_promo.scss
src/components/groups/block-grid/_block-grid.scss

[https://vandam.atlassian.net/browse/WEB-2480](https://vandam.atlassian.net/browse/WEB-2480)

Alter component spacing - venue landing pages

---

src/components/base/icons/readme.md

We removed the dependency during the Fractal v.2.x upgrade. 
[https://vandam.atlassian.net/browse/WEB-1812](https://vandam.atlassian.net/browse/WEB-1812)

Remove svg4everybody link

---

src/components/blocks/newsletter-signup/_newsletter-signup.scss

[https://vandam.atlassian.net/browse/WEB-2328](https://vandam.atlassian.net/browse/WEB-2328)

Standardise background svg across all viewport widths

---

src/components/blocks/events-featured/_events-featured.js
src/components/blocks/events-featured/_events-featured.scss
src/components/blocks/events-featured/events-featured.config.js
src/components/blocks/events-featured/events-featured.html

- big code reduction (and maintenance burden)
- big performance increase with many less event listeners & runtime logic
- no breakpoint magic numbers, tightly coupled to CSS
- no JS dependency
- adds option to scroll/swipe

MAS-394 Events Featured review/revise

---

src/components/blocks/object-image-overlay/_object-image-overlay.scss

Alignment styles fix for close icon on OIC

WEB-2197 - OIC close button center alignment

---

src/components/groups/venue-blog-cards/_venue-blog-cards.scss
src/components/groups/venue-blog-cards/venue-blog-cards.config.js
src/components/groups/venue-blog-cards/venue-blog-cards.html

Styles for new design of single card view on venue landing page.

MAS-358 Venue page blog component single card view design updates

---

src/components/blocks/object-image-overlay/_object-image-overlay.js
src/components/blocks/object-image-overlay/object-image-overlay.config.js

WEB-2423 OIC script update to use images not yet lazy loaded due to being outside of intersection observer.

OIC compatibility updates with lazy loading images

---

src/components/blocks/video-trailer/_video-trailer.scss

Venue landing page, Video trailer padding styles added to a modifier class.

Web 2566 venue landing page video block padding

---

src/components/units/link/_link.scss
src/components/units/link/link.html

[https://vandam.atlassian.net/browse/STC2-369](https://vandam.atlassian.net/browse/STC2-369)
Alter pilcrow to pseudo-element, as advised.

Alter pilcrow to pseudo-element

---

src/components/blocks/event-feature/_event-feature.scss
src/components/blocks/event-feature/event-feature.config.js
src/components/blocks/event-feature/event-feature.html

Tycho branch here - https://github.com/vanda/vam-web/pull/3431

event-feature: remove unnecessary display:none and tidy up [mas-360]

---

src/components/blocks/icon-badge/_icon-badge.scss

[https://vandam.atlassian.net/browse/GCP-53](https://vandam.atlassian.net/browse/GCP-53)

Alter invalid css leading combinator

---

src/components/blocks/object-image-overlay/_object-image-overlay.js
src/components/groups/block-grid/_block-grid.scss
src/components/groups/block-grid/_grid-reveal-more.js

includes WEB-2825, WEB-2708, WEB-2709, WEB-2281

Accessibility 2.2 fixes [WEB-2825, WEB-2708, WEB-2709]

---

src/components/blocks/search-pagination/_search-pagination.js
src/components/blocks/search-pagination/search-pagination.html
src/components/blocks/search-pagination/search-pagination.scss

[https://vandam.atlassian.net/browse/WEB-2858](https://vandam.atlassian.net/browse/WEB-2858)

Alter etc search pagination design

---

src/assets/styles/vam-style.scss
src/components/blocks/file-download/_file-download.scss
src/components/blocks/file-download/file-download.config.js
src/components/blocks/file-download/file-download.html

[https://vandam.atlassian.net/browse/WEB-2938](https://vandam.atlassian.net/browse/WEB-2938)

Add file-download block component

---

src/components/blocks/section-header/_section-header.scss
src/components/blocks/section-header/section-header.config.js
src/components/blocks/section-header/section-header.html

[https://vandam.atlassian.net/browse/GCP-54](https://vandam.atlassian.net/browse/GCP-54)

Update section-header to include alternate section headers

---

src/components/blocks/icon-list/icon-list.config.js
src/components/blocks/icon-list/icon-list.html
src/components/blocks/venue-teaser/venue-teaser.html

[https://vandam.atlassian.net/browse/WEB-2815](https://vandam.atlassian.net/browse/WEB-2815)

Update svg aria attributes to standardised pattern

---

src/components/blocks/venue-teaser/_venue-teaser.scss

[https://vandam.atlassian.net/browse/WEB-2986](https://vandam.atlassian.net/browse/WEB-2986)

Alter venue-teaser list item styling

---

src/components/blocks/object-details/_object-details.scss
src/components/blocks/object-details/object-details.html
src/components/blocks/object-details/object-details.js

[https://vandam.atlassian.net/browse/WEB-2834](https://vandam.atlassian.net/browse/WEB-2834)

Alter read more/less controls to be keyboard accessible

---

src/components/units/button/_button.scss
src/components/units/button/button.config.js

[https://vandam.atlassian.net/browse/STC2-574](https://vandam.atlassian.net/browse/STC2-574)

Stc2 574 add button pill variant

---

src/components/blocks/object-details/_object-details.scss
src/components/blocks/object-details/object-details.js

[https://vandam.atlassian.net/browse/STC2-885](https://vandam.atlassian.net/browse/STC2-885)
etc-frontend:
[https://github.com/vanda/etc-frontend/pull/851](https://github.com/vanda/etc-frontend/pull/851)

Replace read more/less svg icons with css

---

src/components/blocks/icon-list/_icon-list.scss

[https://vandam.atlassian.net/browse/WEB-2941](https://vandam.atlassian.net/browse/WEB-2941)
vam-web:
[https://github.com/vanda/vam-web/pull/3782](https://github.com/vanda/vam-web/pull/3782)

Alter flex-item property to fill available width

---

package-lock.json
package.json

[https://vandam.atlassian.net/browse/WEB-2580](https://vandam.atlassian.net/browse/WEB-2580)

Alter fractal dependencies to devdependencies

---

src/components/blocks/object-image-overlay/_object-image-overlay.js
src/components/blocks/object-image-overlay/_object-image-overlay.scss
src/components/blocks/object-image-overlay/object-image-overlay.config.js
src/components/groups/object-grid/object-grid.config.js
src/components/mixins/breakpoints/_breakpoints.scss

Includes ticket **STC2-824**
Also tied to EtC, but will be merged to `etc-frontend#development` using `vam-fractal#explore-the-collections-development`

STC2-850 oic multisite redesign

---

src/components/blocks/section-header/_section-header.scss

[https://vandam.atlassian.net/browse/WEB-3067](https://vandam.atlassian.net/browse/WEB-3067)
PR vam-web:
[https://github.com/vanda/vam-web/pull/3930](https://github.com/vanda/vam-web/pull/3930)

Alter alternate headings to clear floats

---

src/components/blocks/site-nav/_site-nav.js

[https://vandam.atlassian.net/browse/GCP-49](https://vandam.atlassian.net/browse/GCP-49)
Refactor to replace older code with intersection observer. Tested locally but not deployed for QA as there are no visible or functional changes to test.

Alter class toggle method of mobile nav menu control

---

.stylelintrc.json
package-lock.json
package.json
src/components/blocks/accordion/_accordion.scss
src/components/blocks/events-featured/_events-featured.scss
src/components/blocks/exhibition-promo/_exhibition-promo.scss
src/components/blocks/image-row/_image-row.scss
src/components/blocks/object-card/_object-card.scss
src/components/blocks/object-image-overlay/_object-image-overlay.scss
src/components/blocks/search-form/_search-form.scss
src/components/blocks/section-header/_section-header.scss
src/components/blocks/venue-visit-lead/_venue-visit-lead.scss
src/components/units/checkbox/_checkbox.scss

[https://vandam.atlassian.net/browse/WEB-3206](https://vandam.atlassian.net/browse/WEB-3206)

Dev 14-01-2025 stylelint config alphabetical properties

---

src/components/blocks/exhibition-promo/_exhibition-promo.scss

[https://vandam.atlassian.net/browse/WEB-3203](https://vandam.atlassian.net/browse/WEB-3203)

Dev 14-01-2025 update line clamp properties across components

---

src/components/groups/block-grid/_grid-reveal-more.js
src/components/groups/block-grid/block-grid.html

[https://vandam.atlassian.net/browse/WEB-3168](https://vandam.atlassian.net/browse/WEB-3168)
Tycho PR:
[https://github.com/vanda/vam-web/pull/4076](https://github.com/vanda/vam-web/pull/4076)
EtC PR:
[https://github.com/vanda/etc-frontend/pull/940](https://github.com/vanda/etc-frontend/pull/940)

Web 3168 regression show more button tracking

---

package-lock.json
package.json

[https://vandam.atlassian.net/browse/GCP-60](https://vandam.atlassian.net/browse/GCP-60)
Tested on publication and all appears well locally.

Update surge dependency to v0.24.6

---

src/components/blocks/site-nav/_site-nav.js

[https://vandam.atlassian.net/browse/WEB-3012](https://vandam.atlassian.net/browse/WEB-3012)
Please see comment in above.

Web 3012 remove autofocus search field main menu mobile ios

---

src/components/base/typography/_typography.scss
src/components/blocks/review/_review.scss
src/components/blocks/review/review.html
src/components/blocks/section-header/_section-header.scss
src/components/blocks/section-header/section-header.config.js
src/components/blocks/section-header/section-header.html
src/components/services/_index.scss
src/components/services/light-dark-theme/_light-dark-theme.scss

- WEB-3323 Header Review
- VAM-WEB.GHI-4444 Typography change to all bold line-heights above typography size 4

FtC Collection pg redesign Phase 1

---

src/components/services/imageload/_imageload.js
src/components/services/imageload/_imageload.scss

@methodog this is really your own work but has now been QA checked.
[https://vandam.atlassian.net/browse/STC2-1136](https://vandam.atlassian.net/browse/STC2-1136)
EtC:
[https://github.com/vanda/etc-frontend/pull/1012](https://github.com/vanda/etc-frontend/pull/1012)

imageload: accessibility fixes [STC2-1136]

---

src/components/blocks/carousel/_carousel.scss

[https://vandam.atlassian.net/browse/WEB-3363](https://vandam.atlassian.net/browse/WEB-3363)
Tycho:
[https://github.com/vanda/vam-web/pull/4448](https://github.com/vanda/vam-web/pull/4448)

Alter carousel list margin for safari overflow effect

---

src/components/blocks/site-nav/site-nav.html
src/components/blocks/toggle-set/toggle-set.html

[https://vandam.atlassian.net/browse/WEB-3402](https://vandam.atlassian.net/browse/WEB-3402)
Tycho:
[https://github.com/vanda/vam-web/pull/4489](https://github.com/vanda/vam-web/pull/4489)

Alter nav elements to contain a unique and descriptive label
